---
abstract: unknown
author:
  - 'Martyn J. Pearce '
build_requires:
  Capture::Tiny: 0.13
  File::Temp: 0
  Test::Exception: 0.31
  Test::More: 0.80
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-ProgressBar
no_index:
  directory:
    - t
    - inc
requires:
  Class::MethodMaker: 1.02
  Term::ReadKey: 2.14
resources:
  repository: https://github.com/szabgab/Term-ProgressBar
version: 2.12
